clusterName: "es"
nodeGroup: "ingest"
masterService: "es-master"

lifecycle:
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          # Add a template to adjust number of shards/replicas
          TEMPLATE_NAME=lfdia_set_shards
          INDEX_PATTERN="*"
          SHARD_COUNT=5
          REPLICA_COUNT=1
          ES_URL=http://localhost:9200
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
          curl -XPUT "$ES_URL/_template/$TEMPLATE_NAME" -H 'Content-Type: application/json' -d'{"index_patterns":['\""$INDEX_PATTERN"\"'],"settings":{"number_of_shards":'$SHARD_COUNT',"number_of_replicas":'$REPLICA_COUNT'}}'

# Set role as ingest.
roles:
  master: "false"
  ingest: "true"
  data: "false"
  remote_cluster_client: "false"
  ml: "false"
replicas: 4

# Shrink default JVM heap.
esJavaOpts: "-Xmx1024m -Xms1024m"

# Allocate smaller chunks of memory per pod.
resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  resources:
    requests:
      storage: 10G

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 3
  timeoutSeconds: 15



